# rules csv2pot.py 設定ファイル
input_files = [ '../../Starsector/starsector-core/data/campaign/rules.csv' ]
output_file = 'rules.pot'

pid_version = 'rules.csv Version 0.96a-RC10'

ctxt_id_column = 0

[[extracts]]
column = 4
