# rules csv2pot.py 設定ファイル
input_files    = [ '../../Starsector/starsector-core/data/campaign/rules.csv' ]
input_encoding = 'cp1252'
output_file    = 'rules.csv.pot'

pid_version = 'rules.csv Version 0.96a-RC10'

ctxt_id_column = 0

[[extracts]] # script
column   = 3
patterns = [ 'AddBarEvent' ]
[[extracts]] # text
column = 4
